spring.application.name=lab-inventory-service
server.servlet.context-path=/api/v1
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/db_inventory
spring.datasource.username=postgres
spring.datasource.password=Arun@1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true


eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#eureka.instance.prefer-ip-address=true
#eureka.instance.instance-id=${spring.application.name}:${random.value}