spring.application.name=lab

spring.datasource.url=jdbc:postgresql://localhost:5432/appsecurity
spring.datasource.username=postgres
spring.datasource.password=Arun@1

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=dfds3SFDedre4454543tfdgdgrr6t43543fdffdgfdhfthbgfd
jwt.refreshToken=dsfsfdsfkahuerierfhdshfdsnjk7wuhnbfs85fddsf4e
jwt.expiration=60000
jwt.refreshTokenExpire=1200000